[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
extra_scripts = pre:scripts/auto_port.py
monitor_speed = 115200
upload_speed = 460800
upload_protocol = esptool
lib_deps =
